# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:

services:
    generic.search_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ ~ ]
        tags:      [ { name: 'api_platform.filter', id: 'generic.search' } ]

    generic.numeric_filter:
        parent:    'api_platform.doctrine.orm.range_filter'
        arguments: [ ~ ]
        tags:      [ { name: 'api_platform.filter', id: 'generic.range' } ]

    generic.order_filter:
        parent:    'api_platform.doctrine.orm.order_filter'
        arguments: [ ~ ]
        tags:      [ { name: 'api_platform.filter', id: 'generic.order' } ]

    generic.date_filter:
        parent:    'api_platform.doctrine.orm.date_filter'
        arguments: [ ~ ]
        tags:      [ { name: 'api_platform.filter', id: 'generic.date' } ]