# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:

services:
    task.search_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { id: 'exact', priority: 'exact', name: 'partial', time: 'exact', user: 'exact'  } ]
        tags:      [ { name: 'api_platform.filter', id: 'task.search' } ]

    task.numeric_filter:
        parent:    'api_platform.doctrine.orm.range_filter'
        arguments: [ { priority: ~ } ]
        tags:      [ { name: 'api_platform.filter', id: 'task.range' } ]
